### ISSUE TITLE
Error running snp_utils.py

### ISSUE THREAD

**Issue by DavideGue** [MorrellLAB/morex_reference#1]
I tried to run snp_utils.py using the following command:
./snp_utils.py BLAST -c blast_config.ini -l /path/to/lookup/table/il_lookup_tab.txt
After running few minutes I received the following errors (last few lines):
No query found in GMI_ES02_c16875_166:8.60053e-64
hmm GMI_ES03_c17575_451:0.0
No reference allele for GMI_ES03_c17575_451:0.0, have you run Hsp.get_snp_position() yet?
hmm GMI_ES03_c17575_451:1.12148e-21
No query found in GMI_ES03_c17575_451:1.12148e-21
hmm GMI_ES03_c17575_451:3.55129e-111
No query found in GMI_ES03_c17575_451:3.55129e-111
hmm GMI_ES03_c17575_451:5.21775e-20
No query found in GMI_ES03_c17575_451:5.21775e-20
hmm GMI_ES03_c17575_451:5.21775e-20
No query found in GMI_ES03_c17575_451:5.21775e-20
hmm GMI_ES03_c17370_63:1.92383e-137
Traceback (most recent call last):
  File "./snp_utils.py", line 285, in <module>
    main()
  File "./snp_utils.py", line 262, in main
    snp_list, no_snps, ref_gen, bconf = blast_based(args, lookup_dict)
  File "./snp_utils.py", line 103, in blast_based
    hsp.add_snp(lookup=lookup)
  File "/home/davideg/.local/lib/python3.8/site-packages/overload.py", line 181, in f
    return callable(*usable_args, **_kw)
  File "/home/davideg/Progs/SNP_Utils-master/Objects/blast.py", line 270, in add_snp
    self.add_snp(this_snp=snp.SNP(lookup=lookup, hsp=self))
  File "/home/davideg/.local/lib/python3.8/site-packages/overload.py", line 181, in f
    return callable(*usable_args, **_kw)
  File "/home/davideg/Progs/SNP_Utils-master/Objects/snp.py", line 103, in __init__
    self._position = hsp.get_snp_position(lookup=lookup)
  File "/home/davideg/.local/lib/python3.8/site-packages/overload.py", line 181, in f
    return callable(*usable_args, **_kw)
  File "/home/davideg/Progs/SNP_Utils-master/Objects/blast.py", line 233, in get_snp_position
    return self.get_snp_position(
  File "/home/davideg/.local/lib/python3.8/site-packages/overload.py", line 181, in f
    return callable(*usable_args, **_kw)
  File "/home/davideg/Progs/SNP_Utils-master/Objects/blast.py", line 198, in get_snp_position
    raise NoSNPError("Cannot find the SNP in " + self) # Error out to avoid infinite loops
TypeError: can only concatenate str (not "Hsp") to str
What could have gone wrong?

**Comment by ChaochihL** [comment]
@DavideGue I'm assuming your `blastdbcheck -db` (from ncbi-blast-2.9.0+ tools) for your BLAST database passed without errors? If not, I would make sure that it passes all checks first. I have run into some SNPs that I can't get working successfully for unclear reasons, it was just 2-3 SNPs total that didn't work in my case, so I removed from from the lookup table when they would show a similar error and re-ran SNP_Utils. The rest of the SNPs ran successfully.

**Comment by DavideGue** [comment]
Solved. I removed not working SNPs and run the program succesfully!
Thannk you!

**Comment by ChaochihL** [comment]
Great to hear!
